### ISSUE TITLE
help me, how to install,

### ISSUE THREAD

**Issue by alfonsobp15** [notsogoodsamaritan/pleskcrack#2]
root@cp:/opt/pleskcrack# sudo ./crackplesk.sh
You don't have to, but if you want to you can donate BTC to 13asaKNRnQUmrApr8jbeGxKV6vdHAcGZQk
For more information contact notsogoodsamaritan@tutanota.com
./crackplesk.sh: line 18: /opt/psa/: No such file or directory
[-] Plesk root not found enter root (exp. /opt/psa): /
[+] Copying stuff to /opt/ ..
cp: '.' and '/opt/pleskcrack/.' are the same file
[+] Killing current plesk processes
[+] Blacklisting plesk servers
[+] Activating..
sw-engine : No such file or directory
[+] Replacing sw-engine.service and sw-cp-server.service
[+] Starting sw-engine and sw-cp-server.service
Job for sw-engine.service failed because the control process exited with error code.
See "systemctl status sw-engine.service" and "journalctl -xe" for details.
Job for sw-cp-server.service failed because the control process exited with error code.
See "systemctl status sw-cp-server.service" and "journalctl -xe" for details.
[+] Done, enjoy !!
root@cp:/opt/pleskcrack#

**Comment by notsogoodsamaritan** [comment]
Are you sure plesk is installed ?
get it from https://get.plesk.com/

**Comment by alfonsobp15** [comment]
Ready.... thank so much.
ubuntu 18.04 
![Captura de Pantalla 2019-11-07 a la(s) 19 22 21](https://user-images.githubusercontent.com/12239583/68439127-79e41600-0194-11ea-997c-8eddc7d7ce0b.png)

**Comment by notsogoodsamaritan** [comment]
ok great.
